### ISSUE TITLE
Authentication number is not displayed

### ISSUE THREAD

**Issue by hienlt21293** [kennethaasan/aws-azure-login#248]
I have used this tool just fine for a few months. But today it looks like Microsoft/My organization updated their authentication method. Now, as an additional step, I need to enter a 2-digit number in my phone application to authenticate.

When using aws-azure-login, it shows this log "Open your Authenticator app, and enter the number shown to sign in.​​" but doesn't show any number. 

<img width="885" alt="image" src="https://user-images.githubusercontent.com/33282493/195078013-9616b195-c086-4539-a0c7-3f259a70f59c.png">

**Comment by hienlt21293** [comment]
Just found out that this can easily be solved by using GUI mode
aws-azure-login --mode gui

**Comment by MohamedAsan** [comment]
You can now use the cli(non-gui) mode itself as the auth code is now printed to the terminal/console
The fix is available in [v3.5.1](https://www.npmjs.com/package/aws-azure-login/v/3.5.1)

**Comment by alexFilichkin** [comment]
@MohamedAsan 
It still doesn't work for Docker sportradar/aws-azure-login.
Was Docker image patched?
