### ISSUE TITLE
cheerio update cannot parse SAML XML

### ISSUE THREAD

**Issue by darren-hickling-cognizant** [kennethaasan/aws-azure-login#335]
Cheerio recently published its [first major verson](https://www.npmjs.com/package/cheerio/v/1.0.0), which now yields the the following error after logging in via the GUI:

> TypeError: Cannot read properties of undefined (reading 'load')
    at Object._parseRolesFromSamlResponse ([path]\nodejs-lts\bin\node_modules\aws-azure-login\lib\login.js:663:40)
    at Object.loginAsync ([path]\nodejs-lts\bin\node_modules\aws-azure-login\lib\login.js:379:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

A simple fix for now would be to pin the version in the `package.json`, i.e. `"cheerio": "1.0.0-rc.10"`.

**Comment by jwarhurst** [comment]
Getting same error, thanks for tracking the source.

**Comment by marcobaez-zybooks** [comment]
Also getting the same error. Is there a way to get around this for now until the `package.json` is updated? 

Edit: For anyone else facing this I manually edited the `package.json` to `"cheerio": "1.0.0-rc.10"` then did `npm install` within the `aws-azure-login` and that seems to work!

**Comment by darren-hickling-cognizant** [comment]
@marcobaez-zybooks We used the same hack to get it working 😄

**Comment by christymcgrory** [comment]
Fancy seeing you here @darren-hickling-cognizant, thanks for the hack @marcobaez-zybooks 😄

**Comment by Albert-IV** [comment]
**Update: it doesn't look like NPM respects overrides when installing global modules, the following does not work!**

For anyone using this library as a dependency, you can fix this by adding an `overrides` section to your `package.json` as well.

```json
{
  "overrides": {
    "cheerio": "1.0.0-rc.10"
  }
}
```

[Overrides documentation.](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides)

**Comment by pwjvr** [comment]
@marcobaez-zybooks did the same and it worked - adding the override seemed to cause issues (direct conflict with listed dependency), but that might just be a me thing

**Comment by rohancragg** [comment]
Had to do the same here too, thanks for the workaround

**Comment by rohancragg** [comment]
The fix may be to 

Change `const saml = cheerio.load(samlText, { xmlMode: true });`
to `const saml = cheerio.load(samlText, { xml: true });`

see:
https://cheerio.js.org/docs/advanced/configuring-cheerio#parsing-xml-with-htmlparser2

[Update: ignore this as the documentation seems to be incorrect. `xmlMode` still seems to be the the valid option https://cheerio.js.org/docs/api/interfaces/HTMLParser2Options#xmlmode

**Comment by luven2019** [comment]
@Albert-IV  I am still having the issue even after adding the override to my package.json

**Comment by Albert-IV** [comment]
> @Albert-IV  I am still having the issue even after adding the override to my package.json

This worked when I tested this with a `npm pack && npm i -g package.tar` but users have reported still having this issue. I've updated my original comment.

**Comment by cpmub1** [comment]
i too encountered the same issue & fixed with updating the cheerio version to 1.0.0-rc.12

**Comment by rohancragg** [comment]
Changing line 6 in `login.ts` to `import * as cheerio from "cheerio";` seems to fix this!

**Comment by arpitarora3000** [comment]
@rohancragg where exactly can we find this login.ts file?

**Comment by marcobaez-zybooks** [comment]
@arpitarora3000 `login.ts` can be found here [https://github.com/aws-azure-login/aws-azure-login/blob/main/src/login.ts](https://github.com/aws-azure-login/aws-azure-login/blob/main/src/login.ts)

**Comment by arpitarora3000** [comment]
Hi @marcobaez-zybooks, 

Thank you for a quick reply but what I meant was is this file there somewhere in my aws-azure-login installation directory where I can make the change?

**Comment by rohancragg** [comment]
> Hi @marcobaez-zybooks,
> 
> Thank you for a quick reply but what I meant was is this file there somewhere in my aws-azure-login installation directory where I can make the change?

No, **aws-azure-login** is built and packaged for us to download with NPM, and so the files you will see in the downloaded package will be JavaScript files and not TypeScript.

I am referring to the TypeScript source code for the project which I obtained by cloning this repository with Git as I'm attempting to fix this issue and contribute the fix back to the project. I have submitted a Pull Request (#340) which, once approved by a project maintainer will be built into a new release for you to obtain with NPM. 

What you can do in the meantime to work around this issue is to edit the package.json in the directory where NPM has downloaded it and force NPM to download a specific version of the cheerio dependency package. You could also try to edit the login.js file in the `\lib\` directory but I've not tried this so I can't guarantee that it would work for you, and that change would would need to make will not be the same as the change I made in the login.ts file.

See: [CONTRIBUTING.md](https://github.com/aws-azure-login/aws-azure-login/blob/main/CONTRIBUTING.md) for more info

**Comment by Garethp** [comment]
@rohancragg, thanks for providing the fix in an MR to this project. I've copied that into a fork that I've published on npm called [`aws-azure-auth`](https://github.com/Garethp/aws-azure-auth) to get things working sooner than later

**Comment by rohancragg** [comment]
@Garethp Good idea making a fork. You missed a link to the npm package: https://www.npmjs.com/package/aws-azure-auth
